status = warn
name = TransitPulseLogConfig

appender.console.type = Console
appender.console.name = STDERR
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5p [%t] %c{1.}: %m%n

rootLogger.level = info
rootLogger.appenderRefs = stderr
rootLogger.appenderRef.stderr.ref = STDERR

logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.kafka.name = org.apache.kafka
logger.kafka.level = warn

logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = warn
